// nextjs-app/src/components/csv-uploader.tsx
'use client';

import { useState, useCallback } from 'react';
import { Upload, CheckCircle, Copy, Download, Share2, Check, FileUp, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { uploadCsvFile, type UploadResponse } from '@/lib/api';
import { CsvViewer } from '@/components/csv-viewer';
import { cn } from '@/lib/utils';

interface CsvUploaderProps {
  onFileUploaded?: (result: UploadResponse) => void;
  onViewFile?: (fileUrl: string) => void;
}

export function CsvUploader({ onFileUploaded, onViewFile }: CsvUploaderProps) {
  const [file, setFile] = useState<File | null>(null);
  const [uploading, setUploading] = useState(false);
  const [uploadResult, setUploadResult] = useState<UploadResponse | null>(null);
  const [errorMessage, setErrorMessage] = useState('');
  const [dragActive, setDragActive] = useState(false);
  const [copySuccess, setCopySuccess] = useState(false);
  const [shareSuccess, setShareSuccess] = useState(false);

  const processFile = useCallback((selectedFile: File | null) => {
    if (selectedFile && selectedFile.type === 'text/csv') {
      setFile(selectedFile);
      setErrorMessage('');
    } else {
      setFile(null);
      setErrorMessage('Please select a valid CSV file');
    }
  }, []);

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const selectedFile = e.target.files?.[0] || null;
    processFile(selectedFile);
  };

  const uploadFile = async () => {
    if (!file) {
      setErrorMessage('Please select a file first');
      return;
    }

    setUploading(true);
    setErrorMessage('');

    try {
      const result = await uploadCsvFile(file);
      setUploadResult(result);
      onFileUploaded?.(result);
      setFile(null);
    } catch (error: any) {
      setErrorMessage(error.message || 'An error occurred during upload');
      console.error('Upload error:', error);
    } finally {
      setUploading(false);
    }
  };

  const cancelPreview = () => {
    setFile(null);
    setErrorMessage('');
  };

  const copyToClipboard = async () => {
    if (!uploadResult?.fileUrl) return;

    try {
      await navigator.clipboard.writeText(uploadResult.fileUrl);
      setCopySuccess(true);
      setTimeout(() => setCopySuccess(false), 2000);
    } catch (err) {
      console.error('Failed to copy URL to clipboard:', err);
    }
  };

  const openFileInNewWindow = () => {
    if (uploadResult?.fileUrl) {
      window.open(uploadResult.fileUrl, '_blank');
    }
  };

  const viewFile = () => {
    if (uploadResult?.fileUrl) {
      onViewFile?.(uploadResult.fileUrl);
    }
  };

  const resetUploader = () => {
    setUploadResult(null);
    setFile(null);
  };

  const shareFile = async () => {
    if (!uploadResult?.fileUrl) return;

    const fullUrl = new URL(window.location.href);
    fullUrl.pathname = '/viewer';
    fullUrl.searchParams.set('file', uploadResult.fileUrl);
    const shareUrl = fullUrl.toString();

    if (navigator.share) {
      try {
        await navigator.share({
          title: 'View CSV File',
          url: shareUrl,
        });
        setShareSuccess(true);
        setTimeout(() => setShareSuccess(false), 2000);
      } catch (err) {
        if ((err as Error).name !== 'AbortError') {
          await copyShareUrlToClipboard(shareUrl);
        }
      }
    } else {
      await copyShareUrlToClipboard(shareUrl);
    }
  };

  const copyShareUrlToClipboard = async (url: string) => {
    try {
      await navigator.clipboard.writeText(url);
      setShareSuccess(true);
      setTimeout(() => setShareSuccess(false), 2000);
    } catch (err) {
      console.error('Failed to copy share URL to clipboard:', err);
    }
  };

  const onDragEnter = (e: React.DragEvent) => {
    e.preventDefault();
    setDragActive(true);
  };

  const onDragLeave = (e: React.DragEvent) => {
    e.preventDefault();
    setDragActive(false);
  };

  const onDragOver = (e: React.DragEvent) => {
    e.preventDefault();
  };

  const onDrop = (e: React.DragEvent) => {
    e.preventDefault();
    setDragActive(false);

    if (e.dataTransfer.files && e.dataTransfer.files.length > 0) {
      processFile(e.dataTransfer.files[0]);
    }
  };

  // Show upload success
  if (uploadResult) {
    return (
      <div className="w-full">
        <Card className="border-2 border-green-200 bg-green-50/50 mb-6">
          <CardContent className="pt-6">
            <div className="text-center mb-6">
              <CheckCircle className="w-16 h-16 mx-auto mb-4 text-green-600" />
              <h3 className="text-2xl font-semibold mb-2">Upload Successful!</h3>
              <p className="text-muted-foreground">Your file has been uploaded and is ready to share</p>
            </div>

            <div className="bg-white rounded-lg p-4 mb-6 border">
              <div className="flex items-center gap-2 mb-2">
                <span className="text-sm font-medium text-muted-foreground">File URL:</span>
              </div>
              <div className="flex items-center gap-2">
                <code className="flex-1 text-sm bg-muted p-2 rounded overflow-hidden text-ellipsis whitespace-nowrap">
                  {uploadResult.fileUrl}
                </code>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={copyToClipboard}
                >
                  {copySuccess ? <Check className="h-4 w-4 text-green-600" /> : <Copy className="h-4 w-4" />}
                </Button>
              </div>
            </div>

            <Button
              onClick={shareFile}
              className="w-full mb-4"
              size="lg"
            >
              <Share2 className="mr-2 h-5 w-5" />
              {shareSuccess ? 'Link Copied!' : 'Share This File'}
            </Button>

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
              <Button variant="outline" onClick={viewFile}>
                <Download className="mr-2 h-4 w-4" />
                View
              </Button>
              <Button variant="outline" onClick={openFileInNewWindow}>
                <Download className="mr-2 h-4 w-4" />
                Download
              </Button>
              <Button variant="outline" onClick={resetUploader}>
                <Upload className="mr-2 h-4 w-4" />
                Upload Another
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    );
  }

  // Show preview with unified CsvViewer
  if (file) {
    return (
      <div className="w-full space-y-6">
        <div className="flex items-center justify-between">
          <div>
            <h3 className="text-lg font-semibold">Preview: {file.name}</h3>
            <p className="text-sm text-muted-foreground">Review all your data before uploading</p>
          </div>
          <Button variant="ghost" size="sm" onClick={cancelPreview}>
            <X className="h-4 w-4 mr-2" />
            Cancel
          </Button>
        </div>

        <CsvViewer file={file} title={`Preview: ${file.name}`} />

        {errorMessage && (
          <Alert variant="destructive">
            <AlertDescription>{errorMessage}</AlertDescription>
          </Alert>
        )}

        <div className="flex gap-3">
          <Button
            onClick={uploadFile}
            disabled={uploading}
            className="flex-1"
            size="lg"
          >
            {uploading ? (
              <>
                <Upload className="mr-2 h-5 w-5 animate-spin" />
                Uploading...
              </>
            ) : (
              <>
                <CheckCircle className="mr-2 h-5 w-5" />
                Confirm & Upload
              </>
            )}
          </Button>
          <Button
            variant="outline"
            onClick={cancelPreview}
            disabled={uploading}
            size="lg"
          >
            Cancel
          </Button>
        </div>
      </div>
    );
  }

  // Show file selector
  return (
    <div
      className={cn(
        'border-2 border-dashed rounded-lg p-8 md:p-12 text-center transition-all min-h-[400px] flex flex-col justify-center',
        dragActive ? 'border-primary bg-primary/5' : 'border-border'
      )}
      onDragEnter={onDragEnter}
      onDragLeave={onDragLeave}
      onDragOver={onDragOver}
      onDrop={onDrop}
    >
      <div className="max-w-2xl mx-auto w-full">
        <Upload className="w-16 h-16 mx-auto mb-6 text-primary" />

        <h3 className="text-2xl font-semibold mb-4">Drop your CSV file here</h3>

        <p className="text-lg mb-4">or</p>

        <div className="mb-6">
          <input
            type="file"
            accept=".csv"
            onChange={handleFileChange}
            className="hidden"
            id="file-upload"
          />
          <label htmlFor="file-upload">
            <Button variant="outline" size="lg" className="cursor-pointer" asChild>
              <span>
                <FileUp className="mr-2 h-5 w-5" />
                Select CSV file
              </span>
            </Button>
          </label>
        </div>

        {errorMessage && (
          <Alert variant="destructive" className="max-w-md mx-auto">
            <AlertDescription>{errorMessage}</AlertDescription>
          </Alert>
        )}

        <p className="text-sm text-muted-foreground mt-6">
          You'll be able to preview all data before uploading
        </p>
      </div>
    </div>
  );
}

// frontend/src/components/CsvUploader.vue
<script setup>
import { ref } from 'vue'
import { API_BASE_URL } from '../config'
import { uploadCsvFile } from '../services/api'

const file = ref(null)
const uploading = ref(false)
const uploadResult = ref(null)
const errorMessage = ref('')
const dragActive = ref(false)
const copySuccess = ref(false)
const shareSuccess = ref(false)

const emit = defineEmits(['file-uploaded', 'view-file'])

const handleFileChange = (e) => {
  const selectedFile = e.target.files[0]
  processFile(selectedFile)
}

const processFile = (selectedFile) => {
  if (selectedFile && selectedFile.type === 'text/csv') {
    file.value = selectedFile
    errorMessage.value = ''
  } else {
    file.value = null
    errorMessage.value = 'Please select a valid CSV file'
  }
}

const uploadFile = async () => {
  if (!file.value) {
    errorMessage.value = 'Please select a file first'
    return
  }

  uploading.value = true
  errorMessage.value = ''
  
  try {
    // Use the direct API service to upload the file
    const result = await uploadCsvFile(file.value)
    
    uploadResult.value = result
    emit('file-uploaded', result)
    file.value = null
  } catch (error) {
    errorMessage.value = error.message || 'An error occurred during upload'
    console.error('Upload error:', error)
  } finally {
    uploading.value = false
  }
}

// Copy URL to clipboard
const copyToClipboard = async () => {
  try {
    if (uploadResult.value && uploadResult.value.fileUrl) {
      await navigator.clipboard.writeText(uploadResult.value.fileUrl)
      copySuccess.value = true
      setTimeout(() => {
        copySuccess.value = false
      }, 2000)
    }
  } catch (err) {
    console.error('Failed to copy URL to clipboard:', err)
    // Fallback method for browsers that don't support clipboard API
    const textArea = document.createElement('textarea')
    textArea.value = uploadResult.value.fileUrl
    document.body.appendChild(textArea)
    textArea.select()
    document.execCommand('copy')
    document.body.removeChild(textArea)
    copySuccess.value = true
    setTimeout(() => {
      copySuccess.value = false
    }, 2000)
  }
}

// Open file in new window
const openFileInNewWindow = () => {
  if (uploadResult.value && uploadResult.value.fileUrl) {
    const newWindow = window.open()
    if (newWindow) {
      newWindow.location.href = uploadResult.value.fileUrl
    } else {
      alert('Pop-up blocked. Please allow pop-ups for this site to download the file.')
    }
  }
}

// View file in CSV Viewer
const viewFile = () => {
  if (uploadResult.value && uploadResult.value.fileUrl) {
    emit('view-file', uploadResult.value.fileUrl)
  }
}

// Reset uploader to upload another file
const resetUploader = () => {
  uploadResult.value = null
  file.value = null
}

// Drag and drop handlers
const onDragEnter = (e) => {
  e.preventDefault()
  dragActive.value = true
}

const onDragLeave = (e) => {
  e.preventDefault()
  dragActive.value = false
}

const onDragOver = (e) => {
  e.preventDefault()
}

const onDrop = (e) => {
  e.preventDefault()
  dragActive.value = false
  
  if (e.dataTransfer.files && e.dataTransfer.files.length > 0) {
    processFile(e.dataTransfer.files[0])
  }
}

// Share file functionality
const shareFile = async () => {
  if (uploadResult.value && uploadResult.value.fileUrl) {
    // Create the full URL including the base URL of the application
    const fullUrl = new URL(window.location.href)
    fullUrl.pathname = '/'
    fullUrl.hash = '#/viewer'
    fullUrl.searchParams.set('file', uploadResult.value.fileUrl)
    
    const shareUrl = fullUrl.toString()
    
    // Try to use the Web Share API if available
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'View CSV File',
          text: 'Check out this CSV file',
          url: shareUrl
        })
      } catch (err) {
        // Fallback to copy to clipboard if share fails
        await copyShareUrlToClipboard(shareUrl)
      }
    } else {
      // If Web Share API is not available, copy to clipboard
      await copyShareUrlToClipboard(shareUrl)
    }
  }
}

// Copy share URL to clipboard
const copyShareUrlToClipboard = async (url) => {
  try {
    await navigator.clipboard.writeText(url)
    shareSuccess.value = true
    setTimeout(() => {
      shareSuccess.value = false
    }, 2000)
  } catch (err) {
    console.error('Failed to copy share URL to clipboard:', err)
    // Fallback method for browsers that don't support clipboard API
    const textArea = document.createElement('textarea')
    textArea.value = url
    document.body.appendChild(textArea)
    textArea.select()
    document.execCommand('copy')
    document.body.removeChild(textArea)
    shareSuccess.value = true
    setTimeout(() => {
      shareSuccess.value = false
    }, 2000)
  }
}
</script>

<template>
  <div 
    class="upload-container"
    :class="{ 'drag-active': dragActive }"
    @dragenter="onDragEnter"
    @dragleave="onDragLeave"
    @dragover="onDragOver"
    @drop="onDrop"
  >
    <div v-if="!uploadResult" class="upload-area">
      <v-icon icon="mdi-file-upload-outline" size="xx-large" color="primary" class="mb-5"></v-icon>
      
      <h3 class="text-h5 mb-4">Drop your CSV file here</h3>
      
      <p class="text-body-1 mb-4">or</p>
      
      <v-file-input
        v-model="file"
        label="Select CSV file"
        accept=".csv"
        hide-details
        variant="outlined"
        density="comfortable"
        class="mb-6 file-input"
        @change="handleFileChange"
        prepend-icon="mdi-file-document-outline"
      ></v-file-input>
      
      <v-alert
        v-if="errorMessage"
        type="error"
        variant="tonal"
        class="mt-4 mb-4"
        density="comfortable"
        width="100%"
      >
        {{ errorMessage }}
      </v-alert>
      
      <v-btn
        color="primary"
        size="large"
        block
        :loading="uploading"
        :disabled="!file"
        @click="uploadFile"
        class="mt-4 py-3 text-subtitle-1"
        elevation="2"
      >
        <v-icon start icon="mdi-cloud-upload" class="mr-2"></v-icon>
        Upload Now
      </v-btn>
    </div>
    
    <div v-else class="success-area">
      <v-icon icon="mdi-check-circle" size="xx-large" color="success" class="mb-5"></v-icon>
      
      <h3 class="text-h5 mb-4">Upload Successful!</h3>
      
      <v-card variant="outlined" class="mb-5 pa-4">
        <div class="d-flex align-center">
          <v-icon icon="mdi-link-variant" color="primary" class="mr-2"></v-icon>
          <code class="flex-grow-1 url-code text-body-1">{{ uploadResult.fileUrl }}</code>
          <v-btn
            icon="mdi-content-copy"
            variant="text"
            size="small"
            @click="copyToClipboard"
            :color="copySuccess ? 'success' : ''"
          >
            <v-icon>{{ copySuccess ? 'mdi-check' : 'mdi-content-copy' }}</v-icon>
          </v-btn>
        </div>
      </v-card>
      
      <!-- Share Button (Prominent) -->
      <v-btn
        :color="shareSuccess ? 'success' : 'primary'"
        block
        class="mb-5 py-3 text-subtitle-1"
        @click="shareFile"
        elevation="2"
        size="large"
      >
        <v-icon start class="mr-2">{{ shareSuccess ? 'mdi-check' : 'mdi-share-variant' }}</v-icon>
        {{ shareSuccess ? 'Link Copied!' : 'Share This File' }}
      </v-btn>
      
      <div class="action-buttons">
        <v-btn
          color="primary"
          variant="outlined"
          @click="resetUploader"
          class="action-button py-2"
          size="large"
        >
          <v-icon start icon="mdi-upload" class="mr-1"></v-icon>
          Upload Another
        </v-btn>
        
        <v-btn
          color="info"
          variant="outlined"
          @click="viewFile"
          class="action-button py-2"
          size="large"
        >
          <v-icon start icon="mdi-table-eye" class="mr-1"></v-icon>
          View
        </v-btn>
        
        <v-btn
          color="primary"
          @click="openFileInNewWindow"
          class="action-button py-2"
          size="large"
        >
          <v-icon start icon="mdi-download" class="mr-1"></v-icon>
          Download
        </v-btn>
      </div>
    </div>
  </div>
</template>

<style scoped>
.upload-container {
  border: 2px dashed rgba(0, 0, 0, 0.12);
  border-radius: 8px;
  padding: 3rem;
  text-align: center;
  transition: all 0.3s ease;
  max-width: 100%;
  min-height: 400px;
  display: flex;
  flex-direction: column;
  justify-content: center;
}

.drag-active {
  border-color: var(--v-primary-base);
  background-color: rgba(var(--v-primary-base), 0.05);
}

.upload-area, .success-area {
  max-width: 800px;
  margin: 0 auto;
  width: 100%;
}

.file-input {
  max-width: 100%;
}

.url-code {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  font-size: 1.1rem;
  padding: 0.5rem 0;
}

.action-buttons {
  display: flex;
  flex-wrap: wrap;
  gap: 16px;
  justify-content: center;
  margin-top: 1.5rem;
}

.action-button {
  flex: 1;
  min-width: 160px;
}

@media (max-width: 600px) {
  .upload-container {
    padding: 2rem;
    min-height: 350px;
  }
  
  .upload-area, .success-area {
    max-width: 100%;
  }
  
  .action-buttons {
    flex-direction: column;
    gap: 12px;
  }
  
  .action-button {
    width: 100%;
  }
}
</style>
