// nextjs-app/src/app/page.tsx
'use client';

import { useState } from 'react';
import Link from 'next/link';
import { Github, Upload, Eye, Info, Shield, Cloud, Link as LinkIcon, Clock } from 'lucide-react';
import { CsvUploader } from '@/components/csv-uploader';
import { MobileNav } from '@/components/mobile-nav';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import type { UploadResponse } from '@/lib/api';

export default function Home() {
  const [lastUploadedFile, setLastUploadedFile] = useState<UploadResponse | null>(null);

  const handleFileUploaded = (result: UploadResponse) => {
    setLastUploadedFile(result);
  };

  const handleViewFile = (fileUrl: string) => {
    window.location.href = `/viewer?file=${encodeURIComponent(fileUrl)}`;
  };

  const shareFile = async (fileUrl: string) => {
    const fullUrl = new URL(window.location.href);
    fullUrl.pathname = '/viewer';
    fullUrl.searchParams.set('file', fileUrl);
    const shareUrl = fullUrl.toString();

    if (navigator.share) {
      try {
        await navigator.share({
          title: 'View CSV File',
          url: shareUrl,
        });
      } catch (err) {
        // User cancelled or share failed, copy to clipboard instead
        if ((err as Error).name !== 'AbortError') {
          await navigator.clipboard.writeText(shareUrl);
        }
      }
    } else {
      await navigator.clipboard.writeText(shareUrl);
    }
  };

  return (
    <div className="min-h-screen flex flex-col">
      {/* Navigation */}
      <header className="border-b bg-primary text-primary-foreground">
        <div className="container mx-auto px-4 py-4 flex items-center justify-between">
          <Link href="/" className="text-2xl font-bold">
            Temp CSV
          </Link>
          <nav className="hidden md:flex items-center gap-6">
            <Link href="/" className="hover:underline">
              Home
            </Link>
            <Link href="/viewer" className="hover:underline">
              CSV Viewer
            </Link>
            <Link href="/about" className="hover:underline">
              About
            </Link>
          </nav>
          <div className="flex items-center gap-2">
            <a
              href="https://github.com/open4game/tempcsv"
              target="_blank"
              rel="noopener noreferrer"
              className="hidden md:block hover:opacity-80"
            >
              <Github className="h-6 w-6" />
            </a>
            <MobileNav />
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="flex-1">
        <div className="container mx-auto px-4 py-10 md:py-16">
          <div className="text-center mb-12">
            <h1 className="text-4xl md:text-5xl font-bold mb-4">Temp CSV Online</h1>
            <p className="text-lg md:text-xl text-muted-foreground max-w-3xl mx-auto">
              Upload, view, and share CSV files online without registration.
              Your files are securely stored and easily accessible whenever you need them.
              No login required!
            </p>
          </div>

          {/* Upload Section */}
          <div className="mb-12">
            <h2 className="text-2xl font-semibold mb-4 text-center">Upload your CSV file</h2>
            <CsvUploader onFileUploaded={handleFileUploaded} onViewFile={handleViewFile} />
          </div>

          {/* Recent Activity */}
          {lastUploadedFile && (
            <div className="mb-12">
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Clock className="h-5 w-5" />
                    Recent Activity
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
                    <div className="flex-1 min-w-0">
                      <p className="font-medium mb-1">File Uploaded</p>
                      <code className="text-sm bg-muted p-2 rounded block overflow-hidden text-ellipsis whitespace-nowrap">
                        {lastUploadedFile.fileUrl}
                      </code>
                    </div>
                    <div className="flex gap-2 flex-shrink-0">
                      <Button
                        variant="default"
                        size="sm"
                        onClick={() => shareFile(lastUploadedFile.fileUrl)}
                      >
                        Share
                      </Button>
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => handleViewFile(lastUploadedFile.fileUrl)}
                      >
                        <Eye className="h-4 w-4 mr-1" />
                        View
                      </Button>
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => window.open(lastUploadedFile.fileUrl, '_blank')}
                      >
                        Download
                      </Button>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </div>
          )}

          {/* Features Section */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 mt-16">
            <Card>
              <CardContent className="pt-6 text-center">
                <Shield className="h-12 w-12 mx-auto mb-4 text-primary" />
                <h3 className="text-lg font-semibold mb-2">One Click Upload</h3>
                <p className="text-sm text-muted-foreground">
                  Upload your CSV files with one click, no login required.
                </p>
              </CardContent>
            </Card>

            <Card>
              <CardContent className="pt-6 text-center">
                <Cloud className="h-12 w-12 mx-auto mb-4 text-primary" />
                <h3 className="text-lg font-semibold mb-2">Easy Updates</h3>
                <p className="text-sm text-muted-foreground">
                  Update your files anytime while keeping the same URL.
                </p>
              </CardContent>
            </Card>

            <Card>
              <CardContent className="pt-6 text-center">
                <LinkIcon className="h-12 w-12 mx-auto mb-4 text-primary" />
                <h3 className="text-lg font-semibold mb-2">Shareable Links</h3>
                <p className="text-sm text-muted-foreground">
                  Get permanent links to your files for easy sharing.
                </p>
              </CardContent>
            </Card>

            <Card>
              <CardContent className="pt-6 text-center">
                <Clock className="h-12 w-12 mx-auto mb-4 text-primary" />
                <h3 className="text-lg font-semibold mb-2">Auto Delete</h3>
                <p className="text-sm text-muted-foreground">
                  Files are automatically deleted after 7 days for your privacy.
                </p>
              </CardContent>
            </Card>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t bg-muted/50">
        <div className="container mx-auto px-4 py-8">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div>
              <h3 className="text-lg font-semibold mb-2">Temp CSV</h3>
              <p className="text-sm text-muted-foreground">
                Upload, view, and share CSV files online.
              </p>
            </div>
            <div className="text-center">
              <p className="text-sm text-muted-foreground">
                © {new Date().getFullYear()} Temp CSV
              </p>
            </div>
            <div className="text-right">
              <a
                href="https://github.com/open4game/tempcsv"
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-2 hover:underline"
              >
                <Github className="h-5 w-5" />
                <span>GitHub</span>
              </a>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}

// frontend/src/App.vue
<script setup>
import { ref, computed } from 'vue'
import { API_BASE_URL } from './config'
import CsvUploader from './components/CsvUploader.vue'
import CsvVerifier from './components/CsvVerifier.vue'
import CsvUpdater from './components/CsvUpdater.vue'
import CsvDownloader from './components/CsvDownloader.vue'

const lastUploadedFile = ref(null)
const lastVerifiedFile = ref(null)
const lastUpdatedFile = ref(null)
const activeTab = ref('upload')

const handleFileUploaded = (result) => {
  lastUploadedFile.value = result
  // Automatically switch to the advanced tab after upload
  activeTab.value = 'advanced'
}

const handleFileVerified = (result) => {
  lastVerifiedFile.value = result
}

const handleFileUpdated = (result) => {
  lastUpdatedFile.value = result
}

// Helper function to open file URLs
const openFile = (fileUrl) => {
  if (fileUrl) {
    window.open(fileUrl, '_blank')
  }
}

const showAdvancedFeatures = computed(() => {
  return activeTab.value === 'advanced'
})
</script>

<template>
  <v-app>
    <!-- Navigation Bar -->
    <v-app-bar color="primary" elevation="2">
      <v-container class="d-flex align-center py-0 app-container">
        <v-app-bar-title class="text-h5 font-weight-bold">
          CSV Manager
        </v-app-bar-title>
        <v-spacer></v-spacer>
        <v-tabs v-model="activeTab">
          <v-tab value="upload">Home</v-tab>
          <v-tab value="advanced">Advanced Tools</v-tab>
          <v-tab value="about">About</v-tab>
        </v-tabs>
        <v-spacer></v-spacer>
        <v-btn icon="mdi-github" variant="text" href="https://github.com/open4game/tempcsv" target="_blank"></v-btn>
      </v-container>
    </v-app-bar>

    <v-main>
      <!-- Home/Upload Tab -->
      <v-window v-model="activeTab">
        <v-window-item value="upload">
          <v-container class="py-10 app-container">
            <v-row justify="center">
              <v-col cols="12" class="text-center">
                <h1 class="text-h3 font-weight-bold mb-6">CSV File Manager</h1>
                <p class="text-body-1 mb-8 mx-auto" style="max-width: 800px;">
                  Upload, verify, update, and download CSV files stored in Cloudflare R2.
                  Your files are securely stored and easily accessible whenever you need them.
                </p>
                
                <!-- Main Upload Area -->
                <v-sheet 
                  class="pa-8 mb-8 rounded-lg mx-auto" 
                  color="primary-lighten-5"
                  border
                  style="max-width: 800px;"
                >
                  <h2 class="text-h5 mb-4">Upload your CSV file</h2>
                  <CsvUploader @file-uploaded="handleFileUploaded" />
                </v-sheet>
                
                <!-- Features Section -->
                <v-row class="mt-12 justify-center">
                  <v-col cols="12" sm="4" md="4" class="feature-col">
                    <div class="feature-box">
                      <v-icon icon="mdi-shield-check" size="x-large" color="primary" class="mb-4"></v-icon>
                      <h3 class="text-h6 mb-2">Secure Storage</h3>
                      <p>Your CSV files are securely stored in Cloudflare R2 storage.</p>
                    </div>
                  </v-col>
                  <v-col cols="12" sm="4" md="4" class="feature-col">
                    <div class="feature-box">
                      <v-icon icon="mdi-cloud-sync" size="x-large" color="primary" class="mb-4"></v-icon>
                      <h3 class="text-h6 mb-2">Easy Updates</h3>
                      <p>Update your files anytime while keeping the same URL.</p>
                    </div>
                  </v-col>
                  <v-col cols="12" sm="4" md="4" class="feature-col">
                    <div class="feature-box">
                      <v-icon icon="mdi-link-variant" size="x-large" color="primary" class="mb-4"></v-icon>
                      <h3 class="text-h6 mb-2">Shareable Links</h3>
                      <p>Get permanent links to your files for easy sharing.</p>
                    </div>
                  </v-col>
                </v-row>
              </v-col>
            </v-row>
          </v-container>
        </v-window-item>

        <!-- Advanced Tools Tab -->
        <v-window-item value="advanced">
          <v-container class="py-8 app-container">
            <h2 class="text-h4 mb-6">Advanced Tools</h2>
            
            <div class="tool-section">
              <CsvVerifier @file-verified="handleFileVerified" />
            </div>
            
            <div class="tool-section">
              <CsvUpdater @file-updated="handleFileUpdated" />
            </div>
            
            <div class="tool-section">
              <CsvDownloader />
            </div>
            
            <div class="tool-section" v-if="lastUploadedFile || lastVerifiedFile || lastUpdatedFile">
              <v-card>
                <v-card-title class="text-h5">
                  <v-icon start icon="mdi-history" class="mr-2"></v-icon>
                  Recent Activity
                </v-card-title>
                
                <v-card-text>
                  <v-list>
                    <v-list-item v-if="lastUploadedFile">
                      <template v-slot:prepend>
                        <v-icon icon="mdi-file-upload-outline"></v-icon>
                      </template>
                      <v-list-item-title>File Uploaded</v-list-item-title>
                      <v-list-item-subtitle>
                        <code>{{ lastUploadedFile.fileUrl }}</code>
                      </v-list-item-subtitle>
                      <template v-slot:append>
                        <v-btn
                          icon="mdi-download"
                          variant="text"
                          size="small"
                          @click="openFile(lastUploadedFile.fileUrl)"
                        ></v-btn>
                      </template>
                    </v-list-item>
                    
                    <v-list-item v-if="lastVerifiedFile">
                      <template v-slot:prepend>
                        <v-icon icon="mdi-file-check-outline"></v-icon>
                      </template>
                      <v-list-item-title>File Verified</v-list-item-title>
                      <v-list-item-subtitle>
                        <code>{{ lastVerifiedFile.fileUrl }}</code>
                      </v-list-item-subtitle>
                      <template v-slot:append>
                        <v-btn
                          icon="mdi-download"
                          variant="text"
                          size="small"
                          @click="openFile(lastVerifiedFile.fileUrl)"
                        ></v-btn>
                      </template>
                    </v-list-item>
                    
                    <v-list-item v-if="lastUpdatedFile">
                      <template v-slot:prepend>
                        <v-icon icon="mdi-file-replace-outline"></v-icon>
                      </template>
                      <v-list-item-title>File Updated</v-list-item-title>
                      <v-list-item-subtitle>
                        <code>{{ lastUpdatedFile.fileUrl }}</code>
                      </v-list-item-subtitle>
                      <template v-slot:append>
                        <v-btn
                          icon="mdi-download"
                          variant="text"
                          size="small"
                          @click="openFile(lastUpdatedFile.fileUrl)"
                        ></v-btn>
                      </template>
                    </v-list-item>
                  </v-list>
                </v-card-text>
              </v-card>
            </div>
          </v-container>
        </v-window-item>
        
        <!-- About Tab -->
        <v-window-item value="about">
          <v-container class="py-8 app-container">
            <h2 class="text-h4 mb-6">About CSV Manager</h2>
            <v-card class="mb-6">
              <v-card-text>
                <p class="text-body-1 mb-4">
                  CSV Manager is a simple, efficient tool for managing CSV files in the cloud. 
                  Built with Cloudflare R2 storage, it provides a reliable way to store, update, 
                  and share your CSV files.
                </p>
                <p class="text-body-1 mb-4">
                  This service is designed to be temporary and anonymous, allowing you to quickly 
                  upload and share CSV files without the need for authentication.
                </p>
                <p class="text-body-1">
                  <strong>API Endpoint:</strong> <code>{{ API_BASE_URL }}</code>
                </p>
              </v-card-text>
            </v-card>
            
            <h3 class="text-h5 mb-4">How to Use</h3>
            <v-timeline>
              <v-timeline-item dot-color="primary">
                <template v-slot:opposite>
                  <span class="text-caption">Step 1</span>
                </template>
                <v-card>
                  <v-card-title class="text-h6">Upload a CSV File</v-card-title>
                  <v-card-text>
                    Use the uploader on the home page to upload your CSV file. You'll receive a unique URL.
                  </v-card-text>
                </v-card>
              </v-timeline-item>
              
              <v-timeline-item dot-color="primary">
                <template v-slot:opposite>
                  <span class="text-caption">Step 2</span>
                </template>
                <v-card>
                  <v-card-title class="text-h6">Share or Verify the File</v-card-title>
                  <v-card-text>
                    Share the URL with others or use the Verify tool to check if the file exists.
                  </v-card-text>
                </v-card>
              </v-timeline-item>
              
              <v-timeline-item dot-color="primary">
                <template v-slot:opposite>
                  <span class="text-caption">Step 3</span>
                </template>
                <v-card>
                  <v-card-title class="text-h6">Update if Needed</v-card-title>
                  <v-card-text>
                    Use the Update tool to replace the file while keeping the same URL.
                  </v-card-text>
                </v-card>
              </v-timeline-item>
            </v-timeline>
          </v-container>
        </v-window-item>
      </v-window>
    </v-main>

    <v-footer class="bg-grey-lighten-3">
      <v-container class="app-container">
        <v-row>
          <v-col cols="12" md="4">
            <h3 class="text-h6 mb-2">CSV Manager</h3>
            <p class="text-body-2">
              A simple tool for managing CSV files in the cloud.
            </p>
          </v-col>
          <v-col cols="12" md="4" class="text-center">
            <p class="text-body-2">
              &copy; {{ new Date().getFullYear() }} CSV File Manager
            </p>
          </v-col>
          <v-col cols="12" md="4" class="text-md-end">
            <v-btn icon="mdi-github" variant="text" href="https://github.com/open4game/tempcsv" target="_blank"></v-btn>
          </v-col>
        </v-row>
      </v-container>
    </v-footer>
  </v-app>
</template>

<style>
.v-application {
  font-family: 'Roboto', sans-serif;
}

code {
  background-color: rgba(0, 0, 0, 0.05);
  padding: 2px 4px;
  border-radius: 4px;
  font-family: monospace;
  word-break: break-all;
}

.primary-lighten-5 {
  background-color: #E3F2FD !important;
}

.app-container {
  max-width: 800px !important;
  margin: 0 auto;
  padding-left: 16px;
  padding-right: 16px;
}

.tool-section {
  margin-bottom: 24px;
  width: 100%;
}

.feature-col {
  display: flex;
  justify-content: center;
}

.feature-box {
  max-width: 300px;
}

/* Override Vuetify's grid system for all breakpoints */
.v-col {
  flex-basis: 100% !important;
  max-width: 100% !important;
}

@media (max-width: 600px) {
  .feature-box {
    max-width: 100%;
  }
}
</style>
